### PR TITLE
[Windows] Implement SetResizable for windows

### PR DESCRIPTION
**Pull request by hlwhl**
The SetResizable function of Windows platform is not implemented, implement SetResizable for Windows.

### CODE REVIEW

**Comment by damywise** [comment]
But it's already implemented? Are you facing issues?

**Comment by damywise** [comment]
Current implementation retains the resize border but ignores the attempt to resize it.

**Comment by hlwhl** [comment]
> But it's already implemented? Are you facing issues?

Yes, after called SetResizable(false), users can still change window size by dragging to edge of screen(window snap or something? it's a windows unique feature).  What I added prevent it happen.

**Comment by hlwhl** [comment]
https://user-images.githubusercontent.com/7610615/185604923-4098af3d-dffe-4af2-b507-f9eb1eaa9bca.mp4
added a video for clarification.

**Comment by damywise** [comment]
I see.
I understand, but I'd prefer to look for another solution. This solution glitches on Windows 10. The resize borders are replaced by white colored borders.

**Comment by damywise** [comment]
I'll also try to fix it

**Comment by hlwhl** [comment]
@damywise Got it, will do more research.

**Comment by damywise** [comment]
I have identified the problem and will try to fix it when I have the time soon

**Comment by damywise** [comment]
You can replace the code with this:
(I followed lijy's style and I think this is more readable for me)
```cpp
void WindowManager::SetResizable(const flutter::EncodableMap& args) {
  HWND hWnd = GetMainWindow();
  is_resizable_ =
      std::get<bool>(args.at(flutter::EncodableValue("isResizable")));
  DWORD gwlStyle = GetWindowLong(hWnd, GWL_STYLE);
  if (is_resizable_) {
    gwlStyle |= WS_THICKFRAME;
  } else {
    gwlStyle &= ~WS_THICKFRAME;
  }
  ::SetWindowLong(hWnd, GWL_STYLE, gwlStyle);
}
```
I don't know why your code didn't work before, but when I checked, `WS_OVERLAPPED` was removed wholly instead of just `WS_THICKFRAME`, so `WS_CAPTION`, `WS_SYSMENU`, `WS_MINIMIZEBOX`, and `WS_MAXIMIZEBOX` were also gone.
I just changed the is_resizable to use `|` instead of `&` and replaced `WS_SIZEBOX` with `WS_THICKFRAME` (they're the same thing) and it worked.

**Comment by hlwhl** [comment]
@damywise My bad. Your code works great. Have fixed according to ur suggestion. 🙂

**Comment by lijy91** [comment]
LGTM

**Comment by randal923** [comment]
Hey guys, I am having an isssue where I am setting the setResizable to false in one screen and back to true on another screen but it won't let me set it back to true again, I still can't resize the screen.

**Pull request merged**
