### PR TITLE
[Windows] Fix #112: Add visibleSize and visiblePosition

### LINKED ISSUE #112: [Windows]setAlignment(Alignment.bottomRight) 软件底部被任务栏遮挡
image
上面的Alignment.bottomRight被任务栏遮挡部分. 
image

### PR DESCRIPTION
**Pull request by damywise**
- Add `visibleSize` and `visiblePosition` for `getPrimaryDisplay`

### CODE REVIEW

**Comment by lijy91** [comment]
Should keep size and add visibleSize field.

https://github.com/leanflutter/window_manager/blob/875a617271075c6d30790578b28ea5ea48ea3b5a/macos/Classes/WindowManager.swift#L476-L479

**Comment by damywise** [comment]
Will do

**Comment by damywise** [comment]
Todo: Add visiblePosition

**Comment by damywise** [comment]
Done, I think

**Pull request merged**
